CONFIG_SND_SOC_RT700=m
CONFIG_SND_SOC_RT1308_SDW=m
CONFIG_SND_SOC_RT711=m
CONFIG_SND_SOC_RT715=m



# SPDX-License-Identifier: GPL-2.0
#snd-soc-cx2072x-objs := cx2072x.o
snd-soc-da7213-objs := da7213.o
snd-soc-da7219-objs := da7219.o da7219-aad.o
snd-soc-dmic-objs := dmic.o
snd-soc-es8316-objs := es8316.o
snd-soc-hdac-hdmi-objs := hdac_hdmi.o
snd-soc-hdac-hda-objs := hdac_hda.o
snd-soc-max98090-objs := max98090.o
snd-soc-max98357a-objs := max98357a.o
snd-soc-nau8824-objs := nau8824.o
snd-soc-pcm512x-objs := pcm512x.o
snd-soc-pcm512x-i2c-objs := pcm512x-i2c.o
snd-soc-rl6231-objs := rl6231.o
snd-soc-rl6347a-objs := rl6347a.o
snd-soc-rt1011-objs := rt1011.o
snd-soc-rt1015-objs := rt1015.o
snd-soc-rt1308-objs := rt1308.o
snd-soc-rt1308-sdw-objs := rt1308-sdw.o
snd-soc-rt286-objs := rt286.o
snd-soc-rt5640-objs := rt5640.o
snd-soc-rt5645-objs := rt5645.o
snd-soc-rt5651-objs := rt5651.o
snd-soc-rt5670-objs := rt5670.o
snd-soc-rt5677-objs := rt5677.o
snd-soc-rt5677-spi-objs := rt5677-spi.o
snd-soc-rt5682-objs := rt5682.o
snd-soc-rt5682-sdw-objs := rt5682-sdw.o
snd-soc-rt700-objs := rt700.o rt700-sdw.o
snd-soc-rt711-objs := rt711.o rt711-sdw.o
snd-soc-rt715-objs := rt715.o rt715-sdw.o
snd-soc-ts3a227e-objs := ts3a227e.o
snd-soc-wm8804-objs := wm8804.o
snd-soc-wm8804-i2c-objs := wm8804-i2c.o

#obj-$(CONFIG_SND_SOC_CX2072X)	+= snd-soc-cx2072x.o
#obj-$(CONFIG_SND_SOC_DA7213)	+= snd-soc-da7213.o
#obj-$(CONFIG_SND_SOC_DA7219)	+= snd-soc-da7219.o
obj-$(CONFIG_SND_SOC_DMIC)	+= snd-soc-dmic.o
obj-$(CONFIG_SND_SOC_HDAC_HDMI) += snd-soc-hdac-hdmi.o
obj-$(CONFIG_SND_SOC_HDAC_HDA) += snd-soc-hdac-hda.o
obj-$(CONFIG_SND_SOC_RT1308)	+= snd-soc-rt1308.o
obj-$(CONFIG_SND_SOC_RT1308_SDW)	+= snd-soc-rt1308-sdw.o
obj-$(CONFIG_SND_SOC_RT700)     += snd-soc-rt700.o
obj-$(CONFIG_SND_SOC_RT711)     += snd-soc-rt711.o
obj-$(CONFIG_SND_SOC_RT715)     += snd-soc-rt715.o
